### ISSUE TITLE
Ctrl-C isn't handled cleanly

### ISSUE THREAD

**Issue by icolwell-as** [icolwell-as/geoscenarioserver#8]
When I Ctrl-C geoscenario server, it often results in a bunch of unrelated and random errors. This is somewhat expected, but it would be nice to shut down more cleanly, to avoid confusion and keep errors/exceptions out of any possible logs.

**Comment by mantkiew** [comment]
We have improved the orderly shutdowns in most cases: ctrl+c, close the dashboard window, and agent reaching the goal that ends the scenario (see `goal_ends_simulation` tag, for example https://github.com/rodrigoqueiroz/geoscenarioserver/blob/master/scenarios/coretest_scenarios/straightdrive.gs.osm#L27). This ticket can be closed.

**Comment by icolwell-as** [comment]
Nice! I tried the latest master and closing the dashboard works nicely:
```
INFO:GSServer:GeoScenario server START
INFO:GSServer:Btree search locations set (in order) as: ['/home/iancolwell/git/vis/minesim/geoscenarioserver/btrees']
INFO:Actor:Loading GeoScenario file(s): /home/iancolwell/git/vis/minesim/scenarios/test/test_loop.osm
INFO:Actor:Using LocalCartesianProjector
INFO:Actor:Vehicle 1 initialized with PV behavior
WARNING:Actor:Path-based vehicles are only partially supported in GeoScenario Server 1
INFO:Actor:Pedestrian 2 initialized with TP behavior
INFO:Actor:Pedestrian 1 initialized with TP behavior
INFO:GSServer:SIMULATION START
INFO:shm.SimSharedMemoryServer:Shared memory and semaphores created
/home/iancolwell/git/vis/minesim/geoscenarioserver/dash/Dashboard.py:243: UserWarning: Ignoring specified arguments in this call because figure with num: 1 already exists
  fig = plt.figure(Dashboard.MAP_FIG_ID, frameon=False, clear=True)
INFO:GSServer:SIMULATION END
INFO:GSServer:GeoScenario server shutdown
```

But Ctrl-C never seems to get to the "GeoScenario server shutdown" log output, making me wonder if it did close down cleanly/correctly?
```
INFO:GSServer:GeoScenario server START
INFO:GSServer:Btree search locations set (in order) as: ['/home/iancolwell/git/vis/minesim/geoscenarioserver/btrees']
INFO:Actor:Loading GeoScenario file(s): /home/iancolwell/git/vis/minesim/scenarios/test/test_loop.osm
INFO:Actor:Using LocalCartesianProjector
INFO:Actor:Vehicle 1 initialized with PV behavior
WARNING:Actor:Path-based vehicles are only partially supported in GeoScenario Server 1
INFO:Actor:Pedestrian 2 initialized with TP behavior
INFO:Actor:Pedestrian 1 initialized with TP behavior
INFO:GSServer:SIMULATION START
INFO:shm.SimSharedMemoryServer:Shared memory and semaphores created
/home/iancolwell/git/vis/minesim/geoscenarioserver/dash/Dashboard.py:243: UserWarning: Ignoring specified arguments in this call because figure with num: 1 already exists
  fig = plt.figure(Dashboard.MAP_FIG_ID, frameon=False, clear=True)
^CTraceback (most recent call last):
  File "/home/iancolwell/git/vis/minesim/geoscenarioserver/GSServer.py", line 211, in <module>
    start_server(args)
  File "/home/iancolwell/git/vis/minesim/geoscenarioserver/GSServer.py", line 148, in start_server
    while sync_global.tick():
  File "/home/iancolwell/git/vis/minesim/geoscenarioserver/TickSync.py", line 75, in tick
    time.sleep(-drift)      #blocks diff if negative drift
KeyboardInterrupt
```
